### PR TITLE
Update smart-contracts.md

### PR DESCRIPTION
**Pull request by ShankarWarang**
Issues #12

### CODE REVIEW

**Comment by drewstone** [comment]
This is incorrect. That new link does not have anything to do with smart contracts.

**Comment by drewstone** [comment]
You may be looking for https://substrate.dev/docs/en/knowledgebase/smart-contracts/overview

**Comment by ShankarWarang** [comment]
> This is incorrect. That new link does not have anything to do with smart contracts.

> You may be looking for https://substrate.dev/docs/en/knowledgebase/smart-contracts/overview

I didn't find a single mention of SRML on the substrate.dev wiki/docs
SRMLhub portal does have a catalogue of SRMLs. @drewstone

**Comment by thomivy** [comment]
@ShankarWarang Is this repaired/good to merge?

**Comment by ShankarWarang** [comment]
Removed SRMLhub link as Drew suggested.

**Pull request merged**
